### ISSUE TITLE
Stops are lost on editing linked functions

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#129]
If you edit a function which is linked with -watch=both, stops are lost when the function is fixed. My guess is that this is a side-effect of ⎕FIX not preserving stops. I wonder whether ⎕SE.Link.Notify could preserve stops if there are any?

**Comment by nicolas-dyalog** [comment]
It's not clear what you're talking about.
If it's the APL-side editing with ⎕ED, then the guilt is on ⎕SE.Link.Fix and it should be fixable.
If it's the file-size editing then the guilt is on ⎕SE.Link.Notify but then it becomes very hard to track which lines should stop attach to - requires some kind of diff tool which can not be 100% reliable.

**Comment by nicolas-dyalog** [comment]
in the ⎕ED case, it's doable with not watching the directory, because ⎕SE.Link.Fix does ⎕FIX the code and can restore stops afterwards
However, when watching the directory, the file watcher will pick up the file change and ⎕FIX again, so the stop information needs to be stored somewhere.
Alternatively, we could ask ⎕FIX to be clever about it, and preserve existing stops before re-fixing code.

**Comment by mkromberg** [comment]
I think Link.Notify should simply restore the exact same stop lines, 99% of the time that will be OK, certainly a lot better than just losing them all.

**Comment by nicolas-dyalog** [comment]
fixed in link v2.1 (but no automated QA for it yet -see issue #134)
