### ISSUE TITLE
]link.create with Windows path gives strange error message under Linux

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#167]
**Describe the bug**
If you try to run
]link.create # c:\myfolder
Source directory not found: /home/dyalog/c:\myfolder

**To Reproduce**
Start Dyalog v18 under Linux and type the above command.

**Expected behaviour**
Source directory not found: c:\myfolder

**Desktop (please complete the following information):**
 - OS: Linux 6651d43da47b 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 20
20 x86_64 GNU/Linux
 - APL version: 18.0.38756 
 - `⎕SE.Link.Version`: 2.0.3

**Additional context**

**Comment by nicolas-dyalog** [comment]
I disagree. 
 -Linux should not recognise windows paths : "C:\myfolder" is a valid filename.
- Link correctly interprets "C:\myfolder" as a relative filename
- Link correctly displays the absolute filename, so that the user has a chance to know what Link is trying to access, in case the current working directory is not what they believe it is.

The proposed "Source directory not found: c:\myfolder" is bad because it does not tell you :
- that the path is NOT interpreted as a windows absolute path but as a linux relative filename (the user NEEDS to know that !)
- the current working directory that link is implicitly using when looking for "C:\myfolder" which is again confusing for the newbie blissfully unaware of the current working directory.
