### ISSUE TITLE
Please add support for environment-variables

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/link#198]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to type long and detail pathnames, like to use envvars where possible. This also greatly helps to make code "moveable". 

**Describe the solution you'd like**
I think it would be really helpful if ]LINK and ⎕SE.Link would support use of envvars (cross-platform), either embedded into "%" or "$" etc.

**Describe alternatives you've considered**
Compare manually entering
`⎕SE.Link.Import foo((+2 ⎕NQ'.' 'GetEnvironment' 'DYALOG'),'/StartupSession/Link/Watcher.apln')`
to 
⎕SE.Link.Import foo('%DYALOG%/StartupSession/Link/Watcher.apln')

Another alternative would be extending the interpreter to support envvars whenever he looks up a file - but I assumed it could be addresses much faster here.

**Comment by nicolas-dyalog** [comment]
This must be a Dyalog-wide design.
The main problem is the necessity to escape the % or $ character in case it is found in the actual file name. We can't force that to link users, since no other part of APL forces them to do so - there is an implicit Dyalog assumption that file name strings are "exact".

I believe it's reasonable to have your own system to save environement to APL globals, and then do something like 
⎕SE.Link.Import foo(#.Env.DYALOG,'/StartupSession/Link/Watcher.apln')
or
⎕SE.Link.Import foo(#.Env.Replace'%DYALOG%/StartupSession/Link/Watcher.apln')
