### ISSUE TITLE
Please provide installation documentation for LINK on the mac

### ISSUE THREAD

**Issue by xpqz** [Dyalog/link#222]
As far as I can discover, there is no documentation on how to install LINK on the mac. Dyalog is somewhat convoluted in its installation on the Mac, so it's unclear were the LINK files should be copied to.

**Comment by mkromberg** [comment]
I presume you are asking the question because you want to use a later version of Link than the one that is provided with APL itself. I suspect the easiest solution right now is to clone or checkout the Link repository on your Mac, install stand-alone RIDE so that it is easier to set environment variables when starting APL, and then setting an environment variable to the StartupSession folder that was created by the clone or checkout. Something along the lines of:

DYALOGSTARTUPSE=/Users/yourname/link/StartupSession

**Comment by mkromberg** [comment]
See https://dyalog.github.io/link/3.0/Usage/Installation/
