### ISSUE TITLE
Expunge provides a confusing message

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#281]
I executed

```
]LINK.expunge  Foo
```
with `Foo` being a namespace. I got this:

```
Link Warning: ⎕SE.Link.Notify: deleted /path/Foo/Hello.aplf: file does not reflect in a valid namespace
```

I have no idea what this means, but it did delete the namespace as well as its content in the WS and from the file system.

**Comment by mkromberg** [comment]
I can reproduce this and have submitted a PR, it happens when a file system watched "deleted" event arrives for a file which refers to name within a namespace which has been deleted.

The error report provide very little context, it would have been good to know that Foo was a sub-namespace within a Link. I wasted a bit of time trying to reproduce it deleting linked namespaces.
