### ISSUE TITLE
Link.Break can hang when "Pause Threads on Error" is enabled

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#343]
It's not exactly reproducible but I have seen this twice, and I've sent a dump to support@dyalog.com from the moment when the session became unresponsive.

It's my <01915>.

**Comment by dyavc** [comment]
<01920> Kai has sent in a repro which sounds like it is this.  I can repro with 18.0.44311 64-bit on MS Windows and Link 3.0.0 and will log an issue.

**Comment by dyavc** [comment]
I have logged this as 19317: ⎕SE.Link.Break can sometimes cause Dyalog to hang	

I think it only affects 18.0 running Link 3.0.  It seems to be OK in 18.2.

**Comment by dyavc** [comment]
I can now reproduce it in 18.2 as well.  It needs Threads->Pause on error to be ticked in Dyalog.  This is because the WatchEvent thread is then paused when there is an error in another thread. The Dispose hangs  (because the Link FileSystemWatcher is waiting for the callback WatchEvent thread to return).

**Comment by mkromberg** [comment]
We will look at adding some kind of feature to the interpreter that makes the FSW threads not respond to Pause Threads on Error.
