### ISSUE TITLE
Saving arrays with text:plain does not always do what it should

### ISSUE THREAD

**Issue by aplteam** [Dyalog/link#647]
I have `text:plain` in my configuration file.

When I do:
```
 v←'abc' 'xyz'
 ⎕SE.Link.Add'v'
```
Link creates a file `v.vec.apla`. When I do:
```
 v←↑'abc' 'xyz'
 ⎕SE.Link.Add'v'
```
Link creates a file `v.mat.apla`.

But when I do:
```
 v←'abc',(⎕UCS 13),'xyz'
 ⎕SE.Link.Add'v'
```
Link creates a file `v.apla`, NOT the expected `v.CR.apla`.

` 'abc',(⎕UCS 10),'xyz'` and ` 'abc',(⎕UCS 13 10),'xyz'` do not work as expected either.

**Comment by abrudz** [comment]
This is by design. Per [the documentation](https://dyalog.github.io/link/4.0/Usage/Arrays/), for a simple vector to be stored as plain text, it must have *each line terminated by* one of the supported line endings. In your examples, the last line fails to be terminated by the line ending in question. This design was chosen to align with the POSIX standard for text files. See *[Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)* for details.
