### ISSUE TITLE
Review Bootstrap Mechanism

### ISSUE THREAD

**Issue by mkromberg** [Dyalog/link#87]
To enable loading of Link into Dyalog v17.1, an undocumented mechanism driven by the file startup.dyalog was added. This mechanism should be finalised and documented in time for the v18.0 release.

**Comment by lstefano71** [comment]
Sorry if I comment here below. While I agree that formally this issue was solved, I haven't found another one regarding the possibility of sharing the editor callbacks between multiple extensions ("link" being just one of them). The file StartupSession/Dyalog/Hooks.apln seems to contain the code that would enable that. I could not find it used in the current release of "link" (and this may very well be an oversight on my side). Do you plan to use and document the feature so that we can use at the same time "link" and our own extensions to the session? Thank you.

**Comment by mkromberg** [comment]
We did finish and write some documentation, but developed cold feet at the last moment and did not make the docs public. We are happy to make our internal documentation available to anyone who wants to experiment with the functionality in Link 2.0, and will re-consider properly publishing the documentation if that goes well.
